export TELEGRAM_BOT_TOKEN="SUPER_SECRET_TOKEN"
export DATABASE_PASSWORD='SUPER_SECRET_PASSWORD'
export DATABASE_USER='SUPER_SECRET_USER'
export DATABASE_HOST='localhost'
export DATABASE_SCHEMA='SUPER_SECRET_SCHEMA'
export TIMEZONE='UTC'
